# Generated by Django 4.2.5 on 2024-03-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
