# Generated by Django 4.2.5 on 2024-03-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=132)),
                ('phone', models.IntegerField(max_length=12)),
                ('desc', models.TextField(max_length=12)),
                ('date', models.DateField()),
            ],
        ),
    ]
