# Generated by Django 4.2.5 on 2024-03-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_about_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
